import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Privacy Policy — IlmPath',
  description: 'How IlmPath collects, uses, and protects your data.',
};

const SUPPORT = process.env.SUPPORT_EMAIL ?? 'support@ilmpath.com';

export default function PrivacyPage() {
  return (
    <div style={{ maxWidth: '720px', margin: '0 auto', padding: '3rem 1.5rem' }}>
      <div className="mb-4">
        <Link href="/" className="text-xs text-muted hover:underline">
          ← Back to Home
        </Link>
      </div>
      <h1 style={{ fontSize: 'clamp(1.75rem, 3vw, 2.5rem)', fontWeight: 700, marginBottom: '0.5rem' }}>
        Privacy Policy
      </h1>
      <p style={{ color: 'var(--text-muted)', fontSize: '0.875rem', marginBottom: '2.5rem' }}>
        Last updated: July 2026
      </p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem', color: 'var(--text-secondary)', lineHeight: 1.8 }}>
        <section>
          <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, fontSize: '1.1rem', marginBottom: '0.5rem' }}>
            1. Data We Collect
          </h2>
          <p>When you register and submit a payment, we collect:</p>
          <ul style={{ paddingLeft: '1.25rem', marginTop: '0.5rem' }}>
            <li><strong style={{ color: 'var(--text-primary)' }}>Identity:</strong> Full name, email address</li>
            <li><strong style={{ color: 'var(--text-primary)' }}>Contact:</strong> Phone number (provided on payment form)</li>
            <li><strong style={{ color: 'var(--text-primary)' }}>Payment proof:</strong> Screenshot of bank/wallet transaction, transaction ID, amount paid</li>
            <li><strong style={{ color: 'var(--text-primary)' }}>Usage:</strong> Video watch progress (saved automatically)</li>
          </ul>
          <p style={{ marginTop: '0.75rem' }}>We do <strong style={{ color: 'var(--text-primary)' }}>not</strong> collect card numbers or bank account details.</p>
        </section>

        <section>
          <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, fontSize: '1.1rem', marginBottom: '0.5rem' }}>
            2. Where Your Data Is Stored
          </h2>
          <ul style={{ paddingLeft: '1.25rem' }}>
            <li>Account data &amp; payment records: <strong style={{ color: 'var(--text-primary)' }}>MongoDB Atlas</strong> (cloud database)</li>
            <li>Payment screenshots &amp; course videos: <strong style={{ color: 'var(--text-primary)' }}>Cloudflare R2</strong> (private object storage)</li>
          </ul>
          <p style={{ marginTop: '0.75rem' }}>
            All stored files are private — they are never publicly accessible. Access is controlled
            via short-lived signed URLs generated by our server.
          </p>
        </section>

        <section>
          <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, fontSize: '1.1rem', marginBottom: '0.5rem' }}>
            3. Who Can See Your Data
          </h2>
          <p>
            Only IlmPath administrators can view your name, email, phone, and payment screenshots
            for the purpose of verifying your payment. We do not sell or share your data with
            any third party.
          </p>
        </section>

        <section>
          <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, fontSize: '1.1rem', marginBottom: '0.5rem' }}>
            4. Data Deletion Requests
          </h2>
          <p>
            To request deletion of your account and associated data, email us at{' '}
            <a href={`mailto:${SUPPORT}`} style={{ color: 'var(--brand-400)' }}>{SUPPORT}</a>.
            We will process your request within 7 business days. Note that payment audit records
            may be retained for a reasonable period as required by our internal financial controls.
          </p>
        </section>

        <section>
          <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, fontSize: '1.1rem', marginBottom: '0.5rem' }}>
            5. Cookies
          </h2>
          <p>
            We use a single secure session cookie for authentication (managed by NextAuth.js).
            No tracking cookies, no analytics cookies, no third-party advertising.
          </p>
        </section>

        <section>
          <h2 style={{ color: 'var(--text-primary)', fontWeight: 600, fontSize: '1.1rem', marginBottom: '0.5rem' }}>
            6. Contact
          </h2>
          <p>
            Privacy questions:{' '}
            <a href={`mailto:${SUPPORT}`} style={{ color: 'var(--brand-400)' }}>{SUPPORT}</a>
          </p>
        </section>
      </div>
    </div>
  );
}
